# Generated by Django 2.2.3 on 2019-08-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=30)),
                ('applicant_id', models.EmailField(max_length=254, unique=True)),
                ('applicant_phone', models.IntegerField(max_length=10, unique=True)),
                ('applicant_exp', models.CharField(max_length=2)),
                ('applicant_domain', models.CharField(max_length=10)),
                ('applicant_cv', models.FilePathField(max_length=30)),
            ],
        ),
    ]
