# Generated by Django 2.2.3 on 2019-08-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190811_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(default='Processing', max_length=10),
        ),
    ]
